I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 244, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/security.rpy", line 82, in script call
    call main_menu
  File "game/security.rpy", line 82, in script call
    call main_menu
  File "game/security.rpy", line 82, in script call
    call main_menu
  [Previous line repeated 501228 more times]
  File "game/security.rpy", line 81, in script
    label main_menu:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 244, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/security.rpy", line 82, in script call
    call main_menu
  File "game/security.rpy", line 82, in script call
    call main_menu
  File "game/security.rpy", line 82, in script call
    call main_menu
  [Previous line repeated 501228 more times]
  File "game/security.rpy", line 81, in script
    label main_menu:
  File "C:\Users\Aris\Documents\renpy-8.3.7-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Arisization Project Version_0.0.5
Thu Aug 21 22:17:08 2025
